// <auto-generated />
using System;
using AiWebSiteWatchDog.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AiWebSiteWatchDog.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250926123731_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("AiWebSiteWatchDog.Domain.Entities.EmailSettings", b =>
                {
                    b.Property<string>("SenderEmail")
                        .HasColumnType("TEXT");

                    b.Property<string>("SenderName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("SenderEmail");

                    b.ToTable("EmailSettings");
                });

            modelBuilder.Entity("AiWebSiteWatchDog.Domain.Entities.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("AiWebSiteWatchDog.Domain.Entities.UserSettings", b =>
                {
                    b.Property<string>("EmailRecipient")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailSettingsSenderEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("EmailRecipient");

                    b.HasIndex("EmailSettingsSenderEmail")
                        .IsUnique();

                    b.ToTable("UserSettings");
                });

            modelBuilder.Entity("AiWebSiteWatchDog.Domain.Entities.WatchTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastChecked")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastResult")
                        .HasColumnType("TEXT");

                    b.Property<string>("Schedule")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TaskPrompt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("WatchTasks");
                });

            modelBuilder.Entity("AiWebSiteWatchDog.Infrastructure.Persistence.GoogleOAuthToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EncryptedJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("GoogleOAuthTokens");
                });

            modelBuilder.Entity("AiWebSiteWatchDog.Domain.Entities.UserSettings", b =>
                {
                    b.HasOne("AiWebSiteWatchDog.Domain.Entities.EmailSettings", "EmailSettings")
                        .WithOne()
                        .HasForeignKey("AiWebSiteWatchDog.Domain.Entities.UserSettings", "EmailSettingsSenderEmail")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmailSettings");
                });
#pragma warning restore 612, 618
        }
    }
}
